trigger:
- main

variables:
  azureSubscription: '49cf99f3-ffc8-4c5b-a65b-cdcbf794b95a'
  webAppName: 'insuranceportal'
  environmentName: 'insuranceportal'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      name: Default        # Use your self-hosted agent pool
      demands:
        - maven
        - java
    steps:
    - checkout: self      # ensures your repo is downloaded

    # Install JDK 21
    - task: JavaToolInstaller@0
      displayName: 'Install JDK 21'
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    # Maven build
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/customer/pom.xml' 
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '21'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'

    # Copy build artifacts
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/customer/target'
        Contents: '*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - upload: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      name: Default   # Self-hosted agent pool can also be used
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: insuranceportal'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/*.jar'
