pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository

steps:
# 1. Checkout code
- checkout: self
  clean: true

# 2. Cache Maven dependencies
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: $(MAVEN_CACHE_FOLDER)
    cacheHitVar: MAVEN_CACHE_RESTORED

# 3. Set up JDK 21
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# 4. Build Spring Boot project with parallel threads
- script: |
    mvn clean package -T 1C -DskipTests
  displayName: 'Build Maven Project (skip tests, parallel)'

# 5. Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/*.jar'
    ArtifactName: 'springboot-backend'
    publishLocation: 'Container'
