import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { isElementAccessExpression } from 'typescript';
import { PolicyService } from '../../service/policy-service';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { CommonModule } from '@angular/common';
import { MatDivider, MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-create-policy',
  imports: [MatFormFieldModule, MatInputModule, MatSelectModule, MatButtonModule, MatCardModule,ReactiveFormsModule,FormsModule,MatCardModule,CommonModule,MatDividerModule,MatIconModule,RouterLink],
  templateUrl: './create-policy.html',
  styleUrl: './create-policy.css'
})


export class CreatePolicy {

  policyForm!: FormGroup;
  message = '';

  constructor(private fb: FormBuilder, private policyService: PolicyService) { }

  ngOnInit() {
    this.policyForm = this.fb.group({
      policyNumber: [''],
      name: [''],
      type: [''],
      coverage: [''],
      premium: [''],
      term: [''],
      description: ['']
    })
}

onSubmit() {
  if(this.policyForm.valid){
     this.policyService.createPolicy(this.policyForm.value).subscribe(
      {
        next:(Response)=> {console.log(Response),
         this.message = 'Policy created successfully!';
        this.policyForm.reset();},
        error:(error)=> console.log("ERROR"),
       
      }
        
     );
  
  }
}



}
export interface Policy {
  id: number;            // auto-generated by backend
  policyNumber: string;  // business identifier visible to user
  name: string;          // policy name
  type: string;          // e.g., Health, Life, Car
  coverage: number;      // coverage amount
  premium: number;       // premium amount
  term: number;          // term in years
  description: string;   // optional description
}