name: Build and deploy Spring Boot backend to Azure

on:
  push:
    branches:
      - backend-feature   # deploy only when this branch is pushed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      # 3️⃣ Build the Spring Boot backend
      - name: Build backend
        working-directory: ./customer
        run: mvn clean package -DskipTests

      # 4️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: insuranceportal
          publish-profile: ${{ secrets.SPRING_BOOT_SECRET }}
          package: './customer/target/customer-0.0.1-SNAPSHOT.jar'
          slot-name: production
