name: Build and Deploy Angular App to Azure Static Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js 22
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install --prefix cso-ui

      # 4️⃣ Build Angular app (production)
      - name: Build Angular app
        run: npm run build --prefix cso-ui -- --configuration production

      # 5️⃣ Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # optional
          action: "upload"
          app_location: "cso-ui/dist/cso-ui/browser"
          output_location: ""
