name: Build and deploy Angular app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install Angular dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./cso-ui

      # 4️⃣ Build Angular app (production)
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./cso-ui

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 5️⃣ Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'angularui-e3fqeahrg5b5fbfm'   # ✅ exact App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./cso-ui/dist/cso-ui/browser   # ✅ correct build folder
