name: Deploy Angular App to Azure

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install --prefix cso-ui

      # 4. Build Angular App (Angular 17+ puts build in dist/cso-ui/browser)
      - name: Build Angular App
        run: npm run build --prefix cso-ui -- --configuration production

      # 5. Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: angularui-e3fqeahrg5b5fbfm   # your Azure Web App name
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./cso-ui/dist/cso-ui/browser
