name: Build and deploy Angular app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./cso-ui

      # 5️⃣ Build Angular app
      - name: Build Angular app
        run: ng build --configuration production
        working-directory: ./cso-ui

      # 6️⃣ Add web.config for routing
      - name: Add web.config for Azure
        run: |
          cat <<EOL > ./cso-ui/dist/cso-ui/web.config
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="Angular Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
              <staticContent>
                <mimeMap fileExtension=".json" mimeType="application/json" />
              </staticContent>
            </system.webServer>
          </configuration>
          EOL

      # 7️⃣ Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: ./cso-ui/dist/cso-ui

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1️⃣ Download artifact
      - uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: ./dist

      # 2️⃣ Deploy to Azure Web App
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'angularui'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist
